# Generated by Django 3.2.14 on 2022-07-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContextDomain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dom_id', models.CharField(default='', max_length=3)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContextEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ent_id', models.CharField(default='', max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('domain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interface.contextdomain')),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=280)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_key', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('url', models.CharField(default=None, max_length=255, null=True)),
                ('duration_ms', models.IntegerField(default=None, null=True)),
                ('height', models.IntegerField(default=None, null=True)),
                ('preview_image_url', models.CharField(default=None, max_length=255, null=True)),
                ('width', models.IntegerField(default=None, null=True)),
                ('alt_text', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention', models.CharField(max_length=280)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReferencedTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetid', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StreamRules',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=512)),
                ('tag', models.CharField(default=None, max_length=255, null=True)),
                ('active', models.BooleanField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=512)),
                ('author_id', models.CharField(default=None, max_length=255)),
                ('conversation_id', models.CharField(default=None, max_length=255)),
                ('created_at', models.DateTimeField(default=None)),
                ('in_reply_to_user_id', models.CharField(default=None, max_length=255)),
                ('lang', models.CharField(default=None, max_length=255)),
                ('possibly_sensitive', models.BooleanField(default=None)),
                ('reply_settings', models.CharField(default=None, max_length=255)),
                ('source', models.CharField(default=None, max_length=255)),
                ('context', models.ManyToManyField(to='interface.ContextEntity')),
                ('hashtags', models.ManyToManyField(to='interface.Hashtag')),
                ('mentions', models.ManyToManyField(to='interface.Mention')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=None, null=True)),
                ('description', models.CharField(default=None, max_length=255, null=True)),
                ('location', models.CharField(default=None, max_length=255, null=True)),
                ('pinned_tweet_id', models.CharField(default=None, max_length=255, null=True)),
                ('profile_image_url', models.CharField(default=None, max_length=255, null=True)),
                ('protected', models.BooleanField(default=None, null=True)),
                ('url', models.CharField(default=None, max_length=255, null=True)),
                ('verified', models.BooleanField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers_count', models.IntegerField()),
                ('following_count', models.IntegerField()),
                ('tweet_count', models.IntegerField()),
                ('listed_count', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.user')),
            ],
        ),
        migrations.CreateModel(
            name='TweetMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('retweet_count', models.IntegerField()),
                ('reply_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('quote_count', models.IntegerField()),
                ('tweetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TrackedTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('metrics_per_update', models.IntegerField()),
                ('tweetid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.tweet')),
            ],
        ),
        migrations.CreateModel(
            name='MediaMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField()),
                ('media_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.media')),
            ],
        ),
    ]
